on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'u104477538-prisca'
          server: 'access868316597.webspace-data.io'
          ssh_private_key: ${{ secrets.FTP_PASSWORD }}
          local_path: './static/*'
          remote_path: '/var/www/app'
          args: '-o ConnectTimeout=5'
